[package]
name = "scone-keystore"
version.workspace = true
edition.workspace = true

[dependencies]
scone-crypto.workspace = true
thiserror.workspace = true
chacha20poly1305.workspace = true
argon2.workspace = true
zeroize = { version = "1.8", features = ["derive"] }
getrandom.workspace = true
bip39 = { version = "2", features = ["zeroize"] }

[dev-dependencies]
tempfile.workspace = true
